### ISSUE TITLE
Skill Proficiencies Don't Show and are Locked in Edit

### ISSUE THREAD

**Issue by DaveyJones13** [dragonman117/ddb-alchemy-tools-app#10]
The imported NPC skill proficiencies are not present and when editing the NPC, the skill dropdown only includes the 'Remove' option that does not remove the listed skill. The below creature is a Groff with skill prof in Perception and Stealth.

![image](https://user-images.githubusercontent.com/129871475/230122789-107328c3-e3f6-4f5f-adf8-5d9b996583a9.png)

**Comment by dragonman117** [comment]
So I detected and identified a few idiosyncrasies for skills in Alchemy. 

When a mosnter is added, Alchemy copies unique set of the D&D default skills to use in the drop down for adding a skill. So I added the same default list, and added an import to bring over the values from D&D beyond monster export. That said I did identify a new bug in the system: any mosnter with a skill expertise will not properly copy over. As far as I have been able to identify, there is no flag for this on skills in the d&d beyond API (key monster example is Adult Red Dragon). However as the majority of monsters this works fine on, I am going to publish this as a part of 0.2.1, close this issue, and open a new specific bug to track this as I work to identify a fix.
