### ISSUE TITLE
Character Download Error - Archaic

### ISSUE THREAD

**Issue by DaveyJones13** [dragonman117/ddb-alchemy-tools-app#5]
User attempted to download the json for the below linked character. After 5+ minutes, App continued to load download. Process was cancelled by user.

https://www.dndbeyond.com/monsters/2160296-archaic

**Comment by DaveyJones13** [comment]
User had the same issue with these links.
Art Elemental - https://www.dndbeyond.com/monsters/2160297-art-elemental-mascot
Aarakocra - https://www.dndbeyond.com/monsters/17100-aarakocra
Ancient Crystal Dragon - https://www.dndbeyond.com/monsters/2059691-ancient-crystal-dragon
Ambush Drake - https://www.dndbeyond.com/monsters/17466-ambush-drake

Also used these links with success:
Goblin - https://www.dndbeyond.com/monsters/16907-goblin
Bandit - https://www.dndbeyond.com/monsters/16798-bandit
Deva - https://www.dndbeyond.com/monsters/16840-deva

All successful downloads are creatures from the free basic rules. Seems like there is an issue connecting to purchased content or to the user account.

**Comment by dragonman117** [comment]
Initial fix was applied in 0.2.1-RC, but as it seems to have fixed this issue i'm closing with 0.2.1 release
