### ISSUE TITLE
Speed listed blank

### ISSUE THREAD

**Issue by DaveyJones13** [dragonman117/ddb-alchemy-tools-app#7]
Imported characters using the 0.2.1 version are showing no speed. When opened to edit, 'walk' is selected under Movement Mode and the # of feet is listed under Distance (In Feet). Reselecting or changing these values does not set the movement speed.

![image](https://user-images.githubusercontent.com/129871475/230106548-113619ef-f1e1-48d3-9b95-a12f6dda1043.png)

![image](https://user-images.githubusercontent.com/129871475/230106673-52ed9466-e5e2-485f-a98f-58ac864e2017.png)

**Comment by dragonman117** [comment]
I updated this, there was an undocumented element of alchemy where `walk` was not correctly mapped to the shortcut view, only `walking` displayed in this element. Updating the internal map fixed this issue. This will be published in release 0.2.1 final
