### ISSUE TITLE
Creature Type not Generating Proper Tag

### ISSUE THREAD

**Issue by DaveyJones13** [dragonman117/ddb-alchemy-tools-app#8]
Under 'Type' the correct creature type is listed, but it adds an 's' to the end of the type and does not correlate with an Alchemy creature Type tag. This also applies to the size and the alignment, but those may need to be separate tickets.

![image](https://user-images.githubusercontent.com/129871475/230107841-a67ba0a9-3100-419c-8645-b6b558c4d3cd.png)

![image](https://user-images.githubusercontent.com/129871475/230108075-1b33643b-ff64-48c9-b438-695d6bab576f.png)

**Comment by dragonman117** [comment]
This was a combination of a few small issues. The way I was reporting monsters and monster types was slightly different than alchemy was expecting. After examining the 5e srd version of monsters I fixed the gaps and updated internal monster type maps to better align with alchemy's expected types. This will be published in 0.2.1 final
